allowBuilds:
  '@prisma/engines': false
  prisma: false
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@supabase/auth-js@2.108.1'
  - '@supabase/functions-js@2.108.1'
  - '@supabase/postgrest-js@2.108.1'
  - '@supabase/realtime-js@2.108.1'
  - '@supabase/ssr@0.12.0'
  - '@supabase/storage-js@2.108.1'
  - '@supabase/supabase-js@2.108.1'
